---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: localhost
  remote_user: root

  roles:
    - tomcat

- name: configure and deploy the webservers and application code
  hosts: localhost
  remote_user: root

  roles:
    - tomcat

- name: deploy MySQL and configure the databases
  hosts: localhost
  remote_user: root

  roles:
    - tomcat
  